import React, { useEffect, useState } from 'react';
import SongList from '../components/SongList';
import PlaylistCard from '../components/PlaylistCard';

/**
 * Dashboard Component
 * Main page that displays track filtering interface and results
 * Shows input controls for BPM/cadence filtering and displays matching tracks
 */
const Dashboard = () => {
	const [tracks, setTracks] = useState([]);
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState(null);
	const [cadence, setCadence] = useState(168); // Default to 10:30 pace
	const [tolerance, setTolerance] = useState(10); // Match backend default
  const [paceMinutes, setPaceMinutes] = useState(10);
  const [paceSeconds, setPaceSeconds] = useState(30);
  const [filterMode, setFilterMode] = useState('pace'); // 'pace' or 'bpm'
  const [apiResponse, setApiResponse] = useState(null);
  const [creatingPlaylist, setCreatingPlaylist] = useState(false);
  const [createdPlaylist, setCreatedPlaylist] = useState(null);

  // API call to filter tracks
  const filterTracks = async () => {
    console.log('filterTracks called with:', { filterMode, paceMinutes, paceSeconds, cadence, tolerance });
    
    if (filterMode === 'pace' && (!paceMinutes || paceMinutes < 1)) {
      console.log('Skipping API call - invalid pace minutes:', paceMinutes);
      return;
    }
    if (filterMode === 'bpm' && (!cadence || cadence < 1)) {
      console.log('Skipping API call - invalid cadence:', cadence);
      return;
    }

    console.log('Making API call...');
    setLoading(true);
    setError(null);

    try {
      const payload = filterMode === 'pace' 
        ? { paceMinutes, paceSeconds, tolerance }
        : { targetCadence: cadence, tolerance };

      console.log('Filtering with payload:', payload);

      const response = await fetch('http://localhost:3000/filter/filter', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload)
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const data = await response.json();
      console.log('Filter response:', data);
      console.log('Setting tracks to:', data.tracks);
      
      setApiResponse(data);
      setTracks(data.tracks || []);
      console.log('Tracks state should now be:', data.tracks || []);
      
      // Update cadence display if using pace mode
      if (filterMode === 'pace' && data.targetCadence) {
        setCadence(data.targetCadence);
      }

    } catch (err) {
      console.error('Error filtering tracks:', err);
      setError(`Failed to filter tracks: ${err.message}`);
      setTracks([]);
    } finally {
      setLoading(false);
    }
  };

  // Create a new playlist with filtered tracks
  const createPlaylist = async () => {
    if (!tracks || tracks.length === 0) {
      setError('No tracks available to create playlist');
      return;
    }

    setCreatingPlaylist(true);
    setError(null);

    try {
      const playlistName = apiResponse?.originalPace 
        ? `Running Mix - ${apiResponse.originalPace} pace (${cadence} BPM)`
        : `Running Mix - ${cadence} BPM`;

      const payload = {
        name: playlistName,
        description: `Curated for ${apiResponse?.bpmRange || `${cadence}±${tolerance}`} BPM running cadence. Generated by Paceify.`,
        tracks: tracks.map(track => track.id),
        public: false
      };

      console.log('Creating playlist with payload:', payload);

      const response = await fetch('http://localhost:3000/playlists/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          // In real implementation, add: 'Authorization': `Bearer ${accessToken}`
        },
        body: JSON.stringify(payload)
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const playlistData = await response.json();
      console.log('Playlist created:', playlistData);
      
      setCreatedPlaylist(playlistData);

    } catch (err) {
      console.error('Error creating playlist:', err);
      setError(`Failed to create playlist: ${err.message}`);
    } finally {
      setCreatingPlaylist(false);
    }
  };

  // Auto-filter when inputs change
  useEffect(() => {
    console.log('Dashboard useEffect triggered:', { filterMode, paceMinutes, paceSeconds, cadence, tolerance });
    const timeoutId = setTimeout(() => {
      console.log('About to call filterTracks...');
      filterTracks();
    }, 500); // Debounce API calls

    return () => clearTimeout(timeoutId);
  }, [filterMode, paceMinutes, paceSeconds, cadence, tolerance]);
  
  return (
    <div style={{  // Main container - Full page with gradient background
      minHeight: '100vh',
      background: 'linear-gradient(45deg, #87CEEB 30%, #4682B4 90%)',
      padding: '2rem',
      color: '#FFFFFF'
    }}>
      {/* Content container - Centers and limits width of content */}
      <div style={{
        maxWidth: '1200px',
        margin: '0 auto',
        padding: '2rem',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center'
      }}>
        <h1 style={{
          fontSize: '3.5rem',
          marginBottom: '2rem',
          textAlign: 'center',
          color: '#FFFFFF',
          textShadow: '2px 2px 4px rgba(0,0,0,0.3)',
          fontWeight: 'bold'
        }}>
          Dashboard
        </h1>

        {/* Filter Controls Section - BPM and Tolerance inputs */}
        <div style={{
          background: '#4A4A4A',
          padding: '1.5rem',
          borderRadius: '25px',
          marginBottom: '2rem',
          border: '2px solid white',
          boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
          width: 'fit-content'
        }}>
          <div style={{
            display: 'flex',
            justifyContent: 'center',
            gap: '2rem',
            flexWrap: 'wrap',
            alignItems: 'center'
          }}>
            {/* Filter Mode Toggle */}
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '1rem'
            }}>
              <span style={{ fontSize: '1.1rem', fontWeight: 'bold' }}>Filter by:</span>
              <select
                value={filterMode}
                onChange={e => setFilterMode(e.target.value)}
                style={{
                  padding: '8px 15px',
                  borderRadius: '25px',
                  border: '2px solid white',
                  background: '#191414',
                  fontSize: '1.1rem',
                  color: 'white',
                  fontWeight: 'bold'
                }}
              >
                <option value="pace">Running Pace</option>
                <option value="bpm">Direct BPM</option>
              </select>
            </div>

            {filterMode === 'pace' ? (
              // Pace Input Mode
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '1rem'
              }}>
                <label style={{ fontSize: '1.1rem', fontWeight: 'bold' }}>
                  Pace per mile:
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginTop: '0.5rem' }}>
                    <input
                      type="number"
                      value={paceMinutes}
                      onChange={e => setPaceMinutes(Number(e.target.value))}
                      min="4"
                      max="20"
                      style={{
                        width: '4rem',
                        padding: '8px 12px',
                        borderRadius: '25px',
                        border: '2px solid white',
                        background: '#191414',
                        fontSize: '1.1rem',
                        color: 'white',
                        fontWeight: 'bold',
                        textAlign: 'center'
                      }}
                    />
                    <span style={{ fontSize: '1.2rem', fontWeight: 'bold' }}>:</span>
                    <input
                      type="number"
                      value={paceSeconds}
                      onChange={e => setPaceSeconds(Number(e.target.value))}
                      min="0"
                      max="59"
                      style={{
                        width: '4rem',
                        padding: '8px 12px',
                        borderRadius: '25px',
                        border: '2px solid white',
                        background: '#191414',
                        fontSize: '1.1rem',
                        color: 'white',
                        fontWeight: 'bold',
                        textAlign: 'center'
                      }}
                    />
                  </div>
                </label>
                <div style={{
                  fontSize: '0.9rem',
                  color: '#333',
                  textAlign: 'center'
                }}>
                  <div>≈ {cadence} BPM</div>
                  <div style={{ fontSize: '0.8rem' }}>
                    ({paceMinutes}:{paceSeconds.toString().padStart(2, '0')}/mile)
                  </div>
                </div>
              </div>
            ) : (
              // Direct BPM Mode
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '1rem'
              }}>
                <label style={{ fontSize: '1.1rem', fontWeight: 'bold' }}>
                  Target Cadence (BPM):
                  <input
                    type="number"
                    value={cadence}
                    onChange={e => setCadence(Number(e.target.value))}
                    min="60"
                    max="300"
                    style={{
                      marginLeft: '0.5rem',
                      width: '5rem',
                      padding: '8px 15px',
                      borderRadius: '25px',
                      border: '2px solid white',
                      background: '#191414',
                      fontSize: '1.1rem',
                      color: 'white',
                      fontWeight: 'bold',
                      boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
                    }}
                  />
                </label>
                <div style={{
                  fontSize: '0.9rem',
                  color: '#333',
                  textAlign: 'center'
                }}>
                  <div>≈ {Math.floor(180/cadence)}:{String(Math.round((180/cadence - Math.floor(180/cadence)) * 60)).padStart(2, '0')}/mile</div>
                  <div style={{ fontSize: '0.8rem' }}>
                    ({cadence} BPM)
                  </div>
                </div>
              </div>
            )}

            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '1rem'
            }}>
              <label style={{ fontSize: '1.1rem', fontWeight: 'bold' }}>
                Tolerance: ±
                <input
                  type="number"
                  value={tolerance}
                  onChange={e => setTolerance(Number(e.target.value))}
                  min="1"
                  max="30"
                  style={{
                    marginLeft: '0.5rem',
                    width: '4rem',
                    padding: '8px 15px',
                    borderRadius: '25px',
                    border: '2px solid white',
                    background: '#4A4A4A',
                    fontSize: '1.1rem',
                    color: 'white',
                    fontWeight: 'bold',
                    boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
                  }}
                />
                <span style={{ marginLeft: '0.5rem' }}>BPM</span>
              </label>
            </div>
          </div>

          {/* Status Display */}
          {apiResponse && (
            <div style={{
              marginTop: '1rem',
              padding: '0.5rem',
              background: 'rgba(255, 255, 255, 0.1)',
              borderRadius: '10px',
              textAlign: 'center',
              fontSize: '0.9rem'
            }}>
              <div>
                <strong>Filtering:</strong> {apiResponse.bpmRange} BPM 
                {apiResponse.originalPace && (
                  <span> (from {apiResponse.originalPace} pace)</span>
                )}
              </div>
              <div>
                <strong>Results:</strong> {apiResponse.filteredCount} tracks
                {apiResponse.recommendationsAdded > 0 && (
                  <span style={{ color: '#FFD700' }}> + {apiResponse.recommendationsAdded} recommendations</span>
                )}
              </div>
            </div>
          )}
        </div>
        {/* Track Results Display */}
        <div style={{ width: '100%', maxWidth: '800px' }}>
          {/* Create Playlist Button - Show when we have tracks */}
          {tracks.length > 0 && !createdPlaylist && (
            <div style={{ 
              textAlign: 'center', 
              marginBottom: '1rem'
            }}>
              <button
                onClick={createPlaylist}
                disabled={creatingPlaylist}
                style={{
                  backgroundColor: creatingPlaylist ? '#999' : '#1DB954',
                  color: 'white',
                  border: 'none',
                  borderRadius: '25px',
                  padding: '12px 24px',
                  fontSize: '1.1rem',
                  fontWeight: 'bold',
                  cursor: creatingPlaylist ? 'not-allowed' : 'pointer',
                  boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
                  transition: 'all 0.3s ease'
                }}
                onMouseOver={(e) => {
                  if (!creatingPlaylist) {
                    e.currentTarget.style.backgroundColor = '#1ed760';
                    e.currentTarget.style.transform = 'scale(1.05)';
                  }
                }}
                onMouseOut={(e) => {
                  if (!creatingPlaylist) {
                    e.currentTarget.style.backgroundColor = '#1DB954';
                    e.currentTarget.style.transform = 'scale(1)';
                  }
                }}
              >
                {creatingPlaylist ? '🎵 Creating Playlist...' : `🎵 Create Playlist (${tracks.length} tracks)`}
              </button>
            </div>
          )}

          {/* Created Playlist Success Message */}
          {createdPlaylist && (
            <div style={{
              background: 'rgba(29, 185, 84, 0.1)',
              border: '2px solid #1DB954',
              borderRadius: '12px',
              padding: '1rem',
              marginBottom: '1rem',
              textAlign: 'center'
            }}>
              <h3 style={{ color: '#1DB954', margin: '0 0 0.5rem 0' }}>
                ✅ Playlist Created Successfully!
              </h3>
              <p style={{ margin: '0', fontSize: '1rem' }}>
                <strong>"{createdPlaylist.name}"</strong>
              </p>
              <p style={{ margin: '0.5rem 0 0 0', fontSize: '0.9rem', opacity: '0.8' }}>
                {createdPlaylist.tracks?.length || tracks.length} tracks added to your Spotify library
              </p>
            </div>
          )}

          <SongList 
            tracks={tracks}
            targetCadence={cadence}
            isLoading={loading}
          />
          
          {error && (
            <div style={{ 
              textAlign: 'center',
              padding: '1rem',
              background: 'rgba(255,59,48,0.1)',
              borderRadius: '8px',
              marginTop: '1rem'
            }}>
              <p style={{ color: '#ff3b30', margin: 0 }}>{error}</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
